Web/Models/InboxViewModel.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class ReplyViewModel
    {
        public string ReplyingToMessage { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }

    public class ComposeViewReply
    {
        public string To { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}

Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class FriendsController : Controller
    {
        // GET: Friends
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Web/Controllers/InboxController.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Managers;
using Web.Models;

namespace Web.Controllers
{
    public class InboxController : Controller
    {
        //Add manager
        private readonly IMessageManager _messageManager;

        public InboxController(IMessageManager messageManager)
        {
            //Initialize manager
            _messageManager = messageManager;
        }

        public ActionResult Index()
        {
            var model = _messageManager.RecievedMessages("test-username");
            return View(model);
        }

        [HttpGet]
        public PartialViewResult Inbox()
        {
            var model = _messageManager.RecievedMessages("test-username");
            return PartialView("_Inbox", model);
        }

        [HttpGet]
        public PartialViewResult Outbox()
        {
            var model = _messageManager.SentMessages("test-username");
            return PartialView("_Outbox", model);
        }

        [HttpGet]
        public PartialViewResult Deleted()
        {
            var model = _messageManager.DeletedMessages("test-username");
            return PartialView("_Trash", model);
        }

        [HttpPost]
        public RedirectToRouteResult Delete(int id)
        {
            _messageManager.DeleteMessage(id);
            return RedirectToAction("Inbox");
        }

        [HttpGet]
        public PartialViewResult Compose()
        {
            return PartialView("_Compose", new ComposeViewReply());
        }

        [HttpPost]
        public RedirectToRouteResult Compose(ComposeViewReply model)
        {
            var userMessage = new User_Message() { Sender = "test-username" ,Reciever = model.To, Message = new Message() { Sent_Date = DateTime.Now, Subject = model.Subject, Message1 = model.Message} };
            _messageManager.SendMessage(userMessage);
            return RedirectToAction("Inbox");
        }

        [HttpGet]
        public PartialViewResult Reply(int replyingToId)
        {
            var userMessage = _messageManager.GetUserMessageByMessageId(replyingToId);
            var model = new ReplyViewModel() { ReplyingToMessage = userMessage.Message.Message1, Subject = userMessage.Message.Subject, To = userMessage.Sender};
            return PartialView("_Reply", model);
        }

        [HttpPost]
        public RedirectToRouteResult Reply(ReplyViewModel model)
        {
            var userMessage = new User_Message() { Sender = "test-username", Reciever = model.To, Message = new Message() { Sent_Date = DateTime.Now, Subject = model.Subject, Message1 = model.Message } };
            _messageManager.SendMessage(userMessage);
            return RedirectToAction("Inbox");
        }

        [HttpGet]
        public PartialViewResult ViewInboxMessage(int id)
        {
            var userMessage = _messageManager.GetUserMessageByMessageId(id);
            return PartialView("_ReadInbox", userMessage);
        }

        [HttpGet]
        public PartialViewResult ViewSentMessage(int id)
        {
            var userMessage = _messageManager.GetUserMessageByMessageId(id);
            return PartialView("_ReadSent", userMessage);
        }

        [HttpGet]
        public PartialViewResult ViewDeletedMessage(int id)
        {
            var userMessage = _messageManager.GetUserMessageByMessageId(id);
            return PartialView("_ReadTrash", userMessage);
        }
    }
}

Web/Controllers/LocationProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class LocationProfileController : Controller
    {
        // GET: LocationProfile
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/SubmitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class SubmitController : Controller
    {
        // GET: Submit
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/SubmitPicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class SubmitPicController : Controller
    {
        // GET: SubmitPic
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="../../mymaps/js/lib/d3.js"></script>
<script src="../../mymaps/js/lib/klass.js"></script>
<script src="../../mymaps/js/atlaspr.js"></script>


<style>
    .carousel-inner > .item > img,
    .carousel-inner > .item > a > img {
        width: 70%;
        margin: auto;
    }
</style>


<!--tumbnail-->

<div id="map"></div>

<script type='text/javascript'>
    var my_node = document.getElementById("map");
    new AtlasPR({
        node: my_node
    });
</script>

<div class="col-md-4">

    <div class="row">
        <div class="thumbnail">
            <h3><b>Today's Recommendations</b></h3>
            <!--Carousel Begin-->
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li href="@Url.Action("Index","LocationProfile")" data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>

                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="../../assets/admin/pages/media/gallery/image3.jpg" class="img-responsive" alt="Rincon" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>Rincón</h3>
                            <p>Enjoy of this beatufil beach after a DB exam!</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src="../../assets/admin/pages/media/gallery/image4.jpg" class="img-responsive" alt="Yunque" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>Yunque</h3>
                            <p>Get lost in "El Yunque" if your DB project does'nt run!</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src="../../assets/admin/pages/media/gallery/image5.jpg" class="img-responsive" alt="Morro" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>Morro</h3>
                            <p>Jump from "El Morro" after watching your grade!</p>
                        </div>
                    </div>


                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!--End Carrousel-->
            <div class="caption">

                <p>Know more about this three recommended places!</p>
                <p><a href="#" class="btn btn-primary" role="button">Favorites ♥ </a><a href="#" class="btn btn-default" role="button">Wish List ♣</a></p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="thumbnail">
            <h3><b>Future events</b></h3>
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading">Pool Party | July 7,2016</h4>
                    <p class="list-group-item-text">Enjoy of the best food & drinks!</p>
                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                </a>

                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Salsa Night | Nov 23,2015</h4>
                    <p class="list-group-item-text">Learn how to dance!</p>
                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                </a>
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Code Night| Sept 25,2015</h4>
                    <p class="list-group-item-text">Finish your code to help PR!</p>
                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                </a>
                <a href="#" class="list-group-item" role="button" style="background-color:lightgrey">More Events  </a>




            </div>
        </div>
    </div>


</div>
<div class="col-lg-6">

    <div class="thumbnail">
        <h3><b>News Feed</b></h3>
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!--First Post-->

                <img width="40px" height="40px" src="../../assets/admin/pages/media/users/avatar80_1.jpg" class="img-responsive" alt="Rincon">
                <a href="#">Henry Sanchez</a>
                <p><span class="glyphicon glyphicon-time"></span> Posted on September 25 at 12:49:00 PM</p>


                <hr>
                <!-- Post Content -->
                <p>Visiting Vieques</p>
                <!-- Preview Image -->
                <img src="../../assets/admin/pages/media/gallery/image3.jpg" class="img-responsive" alt="Rincon" width="460" height="345">

                <hr>


                <p>
                    <a href="#" class="btn btn-primary" role="button">Favorites ♥ </a><a href="#" class="btn btn-default" role="button">Wish List ♣</a>
                    <a href="#" class="btn btn-default" role="button">Like </a> <a href="#" class="btn btn-default" role="button">Dislike</a>
                </p>

                <hr>
                <!--Second Post-->
                <img width="40px" height="40px" src="../../assets/admin/pages/media/users/avatar80_2.jpg" class="img-responsive" alt="Rincon">
                <a href="#">Jenny Perez</a>
                <p><span class="glyphicon glyphicon-time"></span> Posted on September 25 at 12:49:00 PM</p>


                <hr>
                <!-- Post Content -->
                <p>Visiting Forest</p>
                <!-- Preview Image -->
                <img src="../../assets/admin/pages/media/gallery/image4.jpg" class="img-responsive" alt="Rincon" width="460" height="345">

                <hr>


                <p>
                    <a href="#" class="btn btn-primary" role="button">Favorites ♥ </a><a href="#" class="btn btn-default" role="button">Wish List ♣</a>
                    <a href="#" class="btn btn-default" role="button">Like </a> <a href="#" class="btn btn-default" role="button">Dislike</a>
                </p>

                <hr>
            </div>
        </div>

    </div>




</div>

Web/Views/Friends/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<row>
    <h2>Friends</h2>
</row>

<row>
    <div class="portlet-body">
        <div class="table-scrollable table-scrollable-borderless">
            <table class="table table-hover table-light">
                <thead>
                    <tr class="uppercase">
                        <th colspan="2">
                            Name
                        </th>
                        <th colspan="2">
                            Remove
                        </th>
                    </tr>
                </thead>
                <tr>
                    <td colspan="2">
                        Gil J Reyes Melendez
                    </td>
                    <td>
                        <a href="javascript:;" class="font-red">
                            <i class="fa fa-minus"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        Johanee Torres Rodriguez
                    </td>
                    <td>
                        <a href="javascript:;" class="font-red">
                            <i class="fa fa-minus"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        Stephan Elias Remy
                    </td>
                    <td>
                        <a href="javascript:;" class="font-red">
                            <i class="fa fa-minus"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        Javi Peseta
                    </td>
                    <td>
                        <a href="javascript:;" class="font-red">
                            <i class="fa fa-minus"></i>
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</row>
        </div>
    </div>
</row>

Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout - Copy.cshtml";
}

<div class="container">
    <!--Log in Form-->
    <div class="row">
        <h4>Description</h4>
    </div>

    <form class="form-signin" >
        <div class="row">
            <h2 class="form-signin-heading">Log in</h2>
        </div>
        <div class="row">
            <label for="inputUsername" class="sr-only">Username</label>
            <input type="text" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
        </div>

        <div class="row">
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        </div>
        <div class="row">
            <a href="@Url.Action("Index","Dashboard")" class="btn btn-sm btn-primary" type="submit">Log in</a>
        </div>

        <div class="row">
            <a href="@Url.Action("Index","SignUp")">Sign up</a>
        </div>
    </form>

</div>

Web/Views/Inbox/Index.cshtml
@model IEnumerable<Entity.GetRecievedMessages_SP_Result>
@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var unreadCount = @Model.Select(m => m.Read_Date == null).Count();
}

@section Styles {
    <link href="~/assets/admin/pages/css/inbox.css" rel="stylesheet" />
    <link href="~/assets/globals/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" />
}

<div class="portlet light">
    <div class="portlet-body">
        <div class="row inbox">
            <div class="col-md-2">
                <ul class="inbox-nav margin-bottom-10">
                    <li class="compose-btn tab-option">
                        <a id="ComposeBtn" href="javascript:;" data-title="Compose" class="btn green">
                            <i class="fa fa-edit"></i> Compose
                        </a>
                        <b></b>
                    </li>
                    <li class="inbox active tab-option">
                        <a id="InboxBtn" href="javascript:;" class="btn" data-title="Inbox">
                            @if (unreadCount == 0)
                            {
                                <span>Inbox</span>
                            }
                            else
                            {
                                <span>Inbox(@unreadCount)</span>
                            }
                        </a>
                        <b></b>
                    </li>
                    <li class="sent tab-option">
                        <a id="SentBtn" class="btn" href="javascript:;" data-title="Sent">
                            Sent
                        </a>
                        <b></b>
                    </li>
                    @*<li class="draft">
                <a id="DraftBtn" class="btn" href="javascript:;" data-title="Draft">
                    Draft
                </a>
                <b></b>
            </li>*@
                    <li class="trash tab-option">
                        <a id="TrashBtn" class="btn" href="javascript:;" data-title="Trash">
                            Trash
                        </a>
                        <b></b>
                    </li>
                </ul>
            </div>
            <div id="Body" class="col-md-10">
                @{Html.RenderPartial("_Inbox");}
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="../../assets/globals/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js" type="text/javascript"></script>
    <script src="../../assets/globals/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js" type="text/javascript"></script>
    <script src="~/Scripts/inbox.js"></script>
    <script>
        jQuery(document).ready(function () {
            Inbox.init();
        });
    </script>
}

Web/Views/Inbox/_Compose.cshtml
@model Web.Models.ComposeViewReply

@using (Html.BeginForm("Compose", "Inbox", FormMethod.Post, new { @class = "inbox-compose form-horizontal", id = "ComposeForm" }))
{
<div class="inbox-form-group mail-to">
    <label class="control-label">To:</label>
    <div class="controls controls-to">
        @Html.TextBoxFor(m => m.To, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.To)
    </div>
</div>
<div class="inbox-form-group">
    <label class="control-label">Subject:</label>
    <div class="controls">
        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Subject)
    </div>
</div>
<div class="inbox-form-group">
    @Html.TextAreaFor(m => m.Message, new { @class = "inbox-editor inbox-wysihtml5 form-control", rows="12" })
</div>
<div class="inbox-compose-btn">
    <button class="btn blue btn-send" type="submit"><i class="fa fa-check"></i>Send</button>
    <button class="btn red btn-discard">Discard</button>
</div>
}

Web/Views/Inbox/_Inbox.cshtml
@model IEnumerable<Entity.GetRecievedMessages_SP_Result>

<div class="inbox-header">
    <h1 class="pull-left">Inbox</h1>
</div>
<div class="inbox-content">
    <table class="table table-striped table-advance table-hover">
        <thead>
        <tr>
            <th colspan="2">
                <span>
                        From
                    </span>
            </th>
            <th colspan="3">
                <span>
                        Subject
                    </span>
            </th>
            <th>
                <span>
                        Date
                    </span>
            </th>
        </tr>
        </thead>
        <tbody>
        @if (!Model.Any())
        {
            <tr>
                <td colspan="6">You have not received any messages...</td>
            </tr>
        }
        else
        {
            foreach (var message in Model)
            {
                var cssString = (message.Read_Date == null) ? "message unread" : "message";

                <tr class="@cssString" data-messageid="@message.Message_Id">
                    <td class="view-message hidden-xs">
                        @message.Sender
                    </td>
                    <td class="view-message ">
                        @message.Subject
                    </td>
                    <td class="view-message text-right">
                        @message.Sent_Date
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

Web/Views/Inbox/_Outbox.cshtml
@model IEnumerable<Entity.GetSentMessages_SP_Result>

<div class="inbox-header">
    <h1 class="pull-left">Sent</h1>
</div>
<div class="inbox-content">
    <table class="table table-striped table-advance table-hover">
        <thead>
            <tr>
                <th colspan="2">
                    <span>
                        To
                    </span>
                </th>
                <th colspan="3">
                    <span>
                        Subject
                    </span>
                </th>
                <th>
                    <span>
                        Date
                    </span>
                </th>
            </tr>
        </thead>
        <tbody>
            @if (!Model.Any())
            {
                <tr>
                    <td colspan="6">You have not sent any messages...</td>
                </tr>
            }
            else
            {
                foreach (var message in Model)
                {
                    <tr class="message-sent" data-messageid="@message.Message_Id">
                        <td class="view-message hidden-xs">
                            @message.Reciever
                        </td>
                        <td class="view-message ">
                            @message.Subject
                        </td>
                        <td class="view-message text-right">
                            @message.Sent_Date
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Web/Views/Inbox/_ReadInbox.cshtml
@model Entity.User_Message
<div class="inbox-header inbox-view-header">
    <h1 class="pull-left">
        @Model.Message.Subject
        <a href="javascript:;" class="goto-inbox-btn">
            Inbox
        </a>
    </h1>
</div>
<div class="inbox-view-info">
    <div class="row">
        <div class="col-md-7">
            <span class="bold">
                @Model.Sender
            </span>
            to <span class="bold">
                me
            </span>
            on @Model.Message.Sent_Date
        </div>
        <div class="col-md-5 inbox-info-btn">
            <div class="btn-group">
                <button id="ReplyBtn" data-messageid="@Model.Message_Id" class="btn blue reply-btn">
                    <i class="fa fa-reply"></i> Reply
                </button>
                <button id="DeletedBtn" data-messageid="@Model.Message_Id" class="btn red delete-btn">
                    <i class="fa fa-trash"></i> Delete
                </button>
                @*<button class="btn blue dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" data-messageid="23" class="reply-btn">
                            <i class="fa fa-reply"></i> Reply
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            <i class="fa fa-arrow-right"></i> Forward
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            <i class="fa fa-print"></i> Print
                        </a>
                    </li>
                    <li class="divider">
                    </li>
                    <li>
                        <a href="javascript:;">
                            <i class="fa fa-ban"></i> Spam
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            <i class="fa fa-trash-o"></i> Delete
                        </a>
                    </li>
                    </ul>*@
            </div>
        </div>
    </div>
</div>
<div class="inbox-view">
    <p>
        @Model.Message.Message1
    </p>
</div>
<hr>

Web/Views/Inbox/_ReadSent.cshtml
@model Entity.User_Message
<div class="inbox-header inbox-view-header">
    <h1 class="pull-left">
        @Model.Message.Subject
        <a href="javascript:;" class="goto-sent-btn">
            Sent
        </a>
    </h1>
</div>
<div class="inbox-view-info">
    <div class="row">
        <div class="col-md-7">
            <span class="bold">
                me
            </span>
            to <span class="bold">
                @Model.Reciever
            </span>
            on @Model.Message.Sent_Date
        </div>
        <div class="col-md-5 inbox-info-btn">
            <div class="btn-group">
                @*<button class="btn blue dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" data-messageid="23" class="reply-btn">
                                <i class="fa fa-reply"></i> Reply
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;">
                                <i class="fa fa-arrow-right"></i> Forward
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;">
                                <i class="fa fa-print"></i> Print
                            </a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="javascript:;">
                                <i class="fa fa-ban"></i> Spam
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;">
                                <i class="fa fa-trash-o"></i> Delete
                            </a>
                        </li>
                        </ul>*@
            </div>
        </div>
    </div>
</div>
<div class="inbox-view">
    <p>
        @Model.Message.Message1
    </p>
</div>
<hr>

Web/Views/SignUp/Index.cshtml
@{
    ViewBag.Title = "Sign up";
    Layout = "~/Views/Shared/_Layout - Copy.cshtml";
}

<div class="container">
    <!--Sign up Form-->

    <form class="form-signin">
        <div class="row">
            <h2 class="form-signin-heading">Sign Up</h2>
        </div>
        <div class="row">
            <label for="inputName" class="sr-only">Name</label>
            <input type="text" id="inputName" class="form-control" placeholder="Name" required autofocus>
        </div>
        <div class="row">
            <label for="inputUsername" class="sr-only">Username</label>
            <input type="text" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
        </div>

        <div class="row">
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        </div>

        <div class="row">
            <label for="inputRePassword" class="sr-only">Re-enter</label>
            <input type="password" id="inputRePassword" class="form-control" placeholder="Re-enter Password" required>
        </div>
        <div class="row">
            <a href="@Url.Action("Index","Dashboard")" class="btn btn-sm btn-primary" type="submit">Sign Up</a>
        </div>
        <div class="row">
            <a class="btn btn-sm btn-primary" type="button" href="@Url.Action("Index","Home")">Cancel</a>
        </div>

    </form>
</div>